name: cli_client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  shared: 
    path: '../cli_shared'
      path: '../cli_server'
    
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
